# Please update the actual username and password according to your lab configuration

ansible_ssh_user: admin
ansible_ssh_pass: none
fanout_mlnx_user: admin
fanout_mlnx_password: admin
fanout_sonic_user: admin
fanout_sonic_password: YourPaSsWoRd

fanout_admin_user: root
fanout_admin_password: none

# Credential for accessing the network cli interface
fanout_network_user: admin
fanout_network_password: none

# Credential for accessing the Linux shell
fanout_shell_user: fanout
fanout_shell_password: fanout

#fanout_tacacs_sonic_user: admin
#fanout_tacacs_sonic_password: password
